### ISSUE TITLE
AllowHighBonusEnchantments not being applied properly

### ISSUE THREAD

**Issue by monochrome-blue** [PixelOutlaw/MythicDrops#257]
Strangely, for whatever reason, AllowHighBonusEnchantments has been doing almost opposite-like behavior of what it should be doing. I have my config set to something like this:

```
displayName: Legendary
displayColor: GOLD
identifierColor: DARK_RED
enchantments:
  safeBaseEnchantments: true
  safeBonusEnchantments: false
  allowHighBaseEnchantments: true
  allowHighBonusEnchantments: true
  baseEnchantments:
  - ARROW_DAMAGE:1:10
  - DURABILITY:10:10
  - ARROW_INFINITE:1:10
  - DAMAGE_ALL:1:10
  bonusEnchantments:
  - PROTECTION_FIRE:1:10
  - ARROW_FIRE:1:10
  - DAMAGE_ARTHROPODS:1:10
  - DURABILITY:1:10
  - PROTECTION_FALL:1:10
  - PROTECTION_EXPLOSIONS:1:10
  - ARROW_KNOCKBACK:1:10
  - ARROW_DAMAGE:1:10
  - DAMAGE_UNDEAD:1:10
  - KNOCKBACK:2:10
  minimumBonusEnchantments: 7
  maximumBonusEnchantments: 10
```

except when that tier config is plugged into the server, it's not allowing any enchantment, except for DURABILITY to be set to a level past their regular enchantable levels. Even stranger, when I set AllowHighBonusEnchantments to false, it allows enchantments to surpass it, though by incredible leaps and bounds! For example, I got the below item when I used /md spawn -t legendary, even though, as you can see, there's no enchantment where the max level is set to higher than 10!

![p2n71px](https://cloud.githubusercontent.com/assets/11543639/13158835/da388084-d65c-11e5-9d83-a9e0fff8fb78.png)

If it helps any, I'm running paperspigot, though the issue has persisted even when using regular spigot, on version 1.8.8.

**Update 1**
The same thing does not happen in regards to baseEnchantments, strangely enough.

**Update 2**
When allowHighBonusEnchantments is set to false, it perceives the max level for bonus enchantments to be 2x the set amount. For example, the the below config, it is possible to obtain up to, but not higher than blast protection 10. This was tested on Spigot 1.8.3 and 1.8.7. 

```
displayName: Legendary
displayColor: GOLD
identifierColor: DARK_RED
enchantments:
  safeBaseEnchantments: true
  safeBonusEnchantments: false
  allowHighBaseEnchantments: true
  allowHighBonusEnchantments: false
  baseEnchantments: []
  bonusEnchantments:
  - PROTECTION_EXPLOSIONS:1:5
  minimumBonusEnchantments: 1
```

**Comment by monochrome-blue** [comment]
Quick update - the same thing does **not** happen in regards to  baseEnchantments, strangely enough.

**Comment by Nunnery** [comment]
You can grab a testable copy of the fix here: [4.0.6-SNAPSHOT](http://maven.tealcube.com/content/repositories/snapshots/com/tealcube/minecraft/bukkit/mythicdrops/4.0.6-SNAPSHOT/mythicdrops-4.0.6-20160220.050910-1.jar)

**Comment by monochrome-blue** [comment]
Awesome!  This fixes the highBonusEnchantments property. 

I think what's causing the other problem in regards to the enchantment levels is due to the enchantment being applied to the item multiple times and adding the two levels. We can see this in the image attached below, since it seems not to be respecting the minimum number of bonus enchantments, but really is, only in the form of duplicate enchantments.

![image](https://cloud.githubusercontent.com/assets/11543639/13196874/f3e34a20-d7a9-11e5-899c-54cd772c61c6.png)

If it helps, here is the config I used in that case:

````
displayName: Legendary
displayColor: GOLD
identifierColor: DARK_RED
enchantments:
  safeBaseEnchantments: true
  safeBonusEnchantments: false
  allowHighBaseEnchantments: true
  allowHighBonusEnchantments: true
  baseEnchantments:
  - ARROW_DAMAGE:1:10
  - DURABILITY:1:10
  - ARROW_INFINITE:1:10
  - DAMAGE_ALL:1:10
  bonusEnchantments:
  - PROTECTION_FIRE:1:10
  - ARROW_FIRE:1:10
  - DAMAGE_ARTHROPODS:1:10
  - DURABILITY:1:10
  - PROTECTION_FALL:1:10
  - PROTECTION_EXPLOSIONS:1:10
  - ARROW_KNOCKBACK:1:10
  - ARROW_DAMAGE:1:10
  - DAMAGE_UNDEAD:1:10
  - KNOCKBACK:1:10
  minimumBonusEnchantments: 7
  maximumBonusEnchantments: 10
````
