### ISSUE TITLE
Socket Gem

### ISSUE THREAD

**Issue by kiritss** [PixelOutlaw/MythicDrops#263]
I realize this probably isn't the most pleasing issue thread, but I have done my fair research and have had no progress so i'll ask few questions here.
1. How can you add commands to the socket gems?
2. Are there anyways to add % chance for success and failure on socket gems and make it wipe enchantment of remove 1 slot if failed?
3. Are there any ways to add more socket slots with use of socket?

Thank you in advance.

**Comment by Nunnery** [comment]
For commands:
```
socket-gems:
    Suicide:
        type: ARMOR
        weight: 100
        prefix: Suicidal
        lore:
        - Makes you commit suicide.
        commands:
        - kill
```

Currently not possible with no plans to implement.

Currently not possible with plans to implement.

**Comment by kiritss** [comment]
Thank you for the quick response! :)

**Comment by kiritss** [comment]
Actually, I just tried it out and the socket with commands do nothing, any ideas?

**Comment by Nunnery** [comment]
You could try doing it as:
```
  SHARD:
    type: ARMOR
    lore:
    - '&4All shall know true suffering'
    commands:
    - PLAYER:md modify lore add &2(Socket)
```
