### ISSUE TITLE
High Tier Unidentified Items Issue

### ISSUE THREAD

**Issue by BurntValentine** [PixelOutlaw/MythicDrops#396]
Getting tiered drops dropping from common mobs such as zombies that they are not set to drop - ie a legendary item from a zombie when they're only set to drop common items.

May be an unidentified item issue - some players have reported it was originally unidentified - but surely they should also follow the same tier system?

MD Version: 5.2.0
Server version: Spigot 1.13.2

**Comment by Nunnery** [comment]
It's an unidentified item issue, and no, they don't follow the same system. Unidentified Items have no way of knowing what they dropped from without adding extra information to the lore of the Unidentified Item.

I do support parsing the last line of lore of the Unidentified Item and getting a tier from that.

I could potentially add support for placeholders in the lore of the item that could be parsed to determine the entity type.

**Comment by BurntValentine** [comment]
Adding the tier to the lore of the item when it drops so it can only become an item in that tier would probably help - it kind of defeats the point of having the tiers set to drop from only certain mob types if an unidentified item dropped by a mob set to only drop common can be a legendary item

**Comment by Nunnery** [comment]
Currently looking at a file structure like this:
```
version: 4.1.0
items:
  identity-tome:
    name: '&5Identity Tome'
    lore:
    - '&7Right-click while holding this tome'
    - '&7over an &dUnidentified Item'
    - '&7to identify it!'
  unidentified:
    name: '&dUnidentified Item'
    lore:
    - '&7Find an &5Identity Tome &7to'
    - '&7identify this item!'
    - ''
    - '%droppedby%'
    - '%allowabletiers%'
    allowable-tiers-prefix: '&7Tiers: (&F'
    allowable-tiers-separator: '&7, &F'
    allowable-tiers-suffix: '&7)'
    dropped-by-prefix: '&7Dropped by: &F'
    dropped-by-suffix: ''
```

Where you could have an Unidentified Item drop from a ZOMBIE configured to drop only common, uncommon, and rare looking like:
![Unidentified Item](https://i.imgur.com/ZXrYe5S.png)

**Comment by Nunnery** [comment]
Final format:
```
version: 4.1.0
options:
  unidentified-items-respect-tier-drops: true
items:
  identity-tome:
    name: '&5Identity Tome'
    lore:
    - '&7Right-click while holding this tome'
    - '&7over an &dUnidentified Item'
    - '&7to identify it!'
  unidentified:
    name: '&dUnidentified Item'
    # You can use the following variables in the lore of an unidentified item:
    # %droppedby% - composed of `dropped-by-prefix`, then the mob type, then `dropped-by-suffix`
    # %allowabletiers% - composed of `allowable-tiers-prefix`, then allowable tiers separated by
    #                    `allowable-tiers-separator`, then `allowable-tiers-suffix`
    # %tier% - composed of `tier-prefix`, then the tier name, then `tier-suffix`
    lore:
    - '&7Find an &5Identity Tome &7to'
    - '&7identify this item!'
    - ''
    - '%droppedby%'
    - '%allowabletiers%'
    allowable-tiers-prefix: '&7Tiers: (&F'
    allowable-tiers-separator: '&7, &F'
    allowable-tiers-suffix: '&7)'
    dropped-by-prefix: '&7Dropped by: &F'
    dropped-by-suffix: ''
    tier-prefix: '&7Tier: &F'
    tier-suffix: ''
```
