### ISSUE TITLE
Cannot Use Items with Enchantments as Repair Costs

### ISSUE THREAD

**Issue by ToppleTheNun** [PixelOutlaw/MythicDrops#420]

**Comment by ToppleTheNun** [comment]
Example repair cost:
```
diamond-boots:
  material-name: DIAMOND_BOOTS
  costs:
    default:
      material-name: DIAMOND
      priority: 0
      amount: 1
      experience-cost: 0
      repair-per-cost: 0.1
      item-name: "&2Repair gem"
```

Example custom item:
```
repairgem:
  material: DIAMOND
  display-name: '&2Repair gem'
  lore:
  - '&eLeft click at an anvil to repair your mythical items!'
  weight: 100
  durability: 1
  chance-to-drop-on-monster-death: 0.01
  broadcast-on-find: false
  custom-model-data: 0
  enchantments:
    MENDING: 1
```
