### ISSUE TITLE
affects-wielder is not respected for AREA gems

### ISSUE THREAD

**Issue by ToppleTheNun** [PixelOutlaw/MythicDrops#444]
This is specifically an issue for gems like the below:
```
 Nube de Veneno III:
    trigger-type: ON_HIT
    all-of-item-groups:
      - armas
    potion-effects:
      POISON:
        intensity: 5
        duration: 20000
        target: AREA
        radius: 10
        chance-to-trigger: 1.0
        affects-wielder: false
        affects-target: true
    weight: 10
    lore:
    - '&a Crea una nube de veneno 20s'
    family: Veneno Plus
    level: 3
```
