### ISSUE TITLE
BUG : Particles from particles-effects key on socketGems.yml are fully bugged

### ISSUE THREAD

**Issue by Corazun** [PixelOutlaw/MythicDrops#451]
Hello, the particles are fully bugged. Firstly the "chance-to-trigger" key seems to didn't work. I think it's calculated only when the player equip the armor cause sometimes the particle is always run and sometimes it's never. Also the particle duration seems infinite and isn't stopped and stacks when the gem is called. And the worst is if the particle was ran and the player dies it will continue to spawn the particles on the player dead location without stopping

Here's my config :

```
Gem I:
    trigger-type: WHEN_HIT
    all-of-item-groups:
    - armor
    potion-effects:
      INCREASE_DAMAGE:
        intensity: 0
        duration: 3100
        chance-to-trigger: 0.1
        target: SELF
        radius: 0
    particle-effects:
        FIREWORKS_SPARK:
            intensity: 1
            duration: 2000
            target: SELF
            chance-to-trigger: 1.0
    weight: 50
```
