### ISSUE TITLE
Tier Not Dropping From Zombie Pigmen

### ISSUE THREAD

**Issue by ToppleTheNun** [PixelOutlaw/MythicDrops#458]
```
enchantments:
  safe-base-enchantments: true
  safe-bonus-enchantments: true
  allow-high-base-enchantments: true
  allow-high-bonus-enchantments: true
  base-enchantments:
  - ARROW_DAMAGE:12:14
  - PROTECTION_ENVIRONMENTAL:19:21
  - PROTECTION_FALL:19:21
  - DURABILITY:19:21
  - ARROW_INFINITE:1:1
  - DAMAGE_ALL:12:14
  - DIG_SPEED:19:21
  - QUICK_CHARGE:2:3
  - PIERCING:2:3
  - LOYALTY:2:3
  bonus-enchantments:
  - LOOT_BONUS_MOBS:9:10
  - LOOT_BONUS_BLOCKS:9:10
  - DAMAGE_ARTHROPODS:12:14
  - DAMAGE_UNDEAD:12:14
  - FIRE_ASPECT:9:10
  - ARROW_FIRE:9:10
  - OXYGEN:9:10
  - WATER_WORKER:9:10
  - DEPTH_STRIDER:9:10
  - MENDING:1:1
  - SWEEPING_EDGE:2:3
  - MULTISHOT:2:3
  - IMPALING:2:3
  - CHANNELING:2:3
  minimum-bonus-enchantments: 4
  maximum-bonus-enchantments: 8
lore:
  minimum-bonus-lore: 0
  maximum-bonus-lore: 0
  bonus-lore:
  - '&eIve got that Summertime Sadness'
  base-lore:
  - '&e&lLike the Stars miss the Sun'
display-name: Summertime Sadness
display-color: YELLOW
identifier-color: YELLOW
maximum-durability: 1.0
minimum-durability: 1.0
maximum-sockets: 6
minimum-sockets: 2
weight: 0.03
chance-to-drop-on-monster-death: 1.0
identity-weight: 1.0
chance-to-have-sockets: 0.9
broadcast-on-find: false
item-types:
  allowed-groups:
  - pickaxe
  - sword
  - axe
  - shovel
  - bow
  - helmet
  - boots
  - chestplate
  - leggings
  - trident
  disallowed-groups:
  - leather
  - chainmail
  - gold
  - iron
  - wood
  - stone
  allowed-material-ids: []
  disallowed-material-ids: []
minimum-distance-from-spawn: -1
maximum-distance-from-spawn: -1
unbreakable: false
version: 1.1.0
attributes:
  minimum-bonus-attributes: 0
  maximum-bonus-attributes: 0
```
