### ISSUE TITLE
Socket Gem Particle Effects Lasting Too Long

### ISSUE THREAD

**Issue by ToppleTheNun** [PixelOutlaw/MythicDrops#459]
Below gem is reported as lasting 1 minute but should only be 4 seconds.

Example Socket Gem:
```
  XBDesire:
    trigger-type: ON_HIT
    all-of-item-groups:
      - Honey_Sword
    potion-effects:
      SLOW:
        intensity: 3
        duration: 4000
        target: OTHER
        radius: 0
        chance-to-trigger: 1.0
        affects-wielder: false
        affects-target: true
    particle-effects:
        LANDING_HONEY:
          intensity: 0
          duration: 4000
          target: OTHER
          radius: 0
          chance-to-trigger: 1.0
          affects-wielder: false
          affects-target: true
    weight: 50
    prefix: Michael's
    lore:
      - "&aYou shall be hindered... "
    family: xbdesire
    Level: 1
```
