### ISSUE TITLE
MD 6.3.0-dev.60f928384 no longer drops unidentified items.

### ISSUE THREAD

**Issue by SirKillian** [PixelOutlaw/MythicDrops#489]
Currently, version 6.3.0-dev.60f928384 no longer drops unidentified items from mobs.

- I used a default identiying.yml file
- Main config settings:
```yaml
drops:
  strategy: single
  item-chance: 1
  tiered-item-chance: 0
  custom-item-chance: 0
  socket-gem-chance: 0
  unidentified-item-chance: 1
  identity-tome-chance: 0
  socket-extender-chance: 0

components:
  identifying-enabled: true
```

Additionally I have 5 Tiers, every tier has "identity-weight:" set. all 5 weights counted together results in 1.0

After 10,000 mobs, 0 unidentified items have dropped.

**Comment by ToppleTheNun** [comment]
Can you please provide one of the tiers?

**Comment by SirKillian** [comment]
```
version: 1.5.0
display-name: Rusty
display-color: GRAY
identifier-color: GRAY
attributes:
  base-attributes: []
  bonus-attributes: []
  minimum-bonus-attributes: 0
  maximum-bonus-attributes: 0
enchantments:
  safe-base-enchantments: false
  safe-bonus-enchantments: false
  allow-high-base-enchantments: true
  allow-high-bonus-enchantments: true
  base-enchantments: []
  bonus-enchantments:
  - ARROW_DAMAGE:1:3
  - ARROW_FIRE:1:3
  - ARROW_INFINITE:1:3
  - ARROW_KNOCKBACK:1:3
  - DAMAGE_ALL:1:3
  - DAMAGE_ARTHROPODS:1:3
  - DAMAGE_UNDEAD:1:3
  - DEPTH_STRIDER:1:3
  - DIG_SPEED:1:3
  - DURABILITY:1:3
  - FIRE_ASPECT:1:3
  - KNOCKBACK:1:3
  - LOOT_BONUS_BLOCKS:1:2
  - LOOT_BONUS_MOBS:1:2
  - LUCK:1:3
  - LURE:1:2
  - OXYGEN:1:3
  - PROTECTION_ENVIRONMENTAL:1:3
  - PROTECTION_EXPLOSIONS:1:3
  - PROTECTION_FALL:1:3
  - PROTECTION_FIRE:1:3
  - PROTECTION_PROJECTILE:1:3
  - SILK_TOUCH:1:3
  - THORNS:1:3
  - WATER_WORKER:1:3
  - FROST_WALKER:1:3
  - SWEEPING_EDGE:1:1
  - MULTISHOT:1:1
  - QUICK_CHARGE:1:3
  - PIERCING:1:1
  minimum-bonus-enchantments: 0
  maximum-bonus-enchantments: 1
  allow-high-relation-enchantments: true
  safe-relation-enchantments: false
lore:
  minimum-bonus-lore: 0
  maximum-bonus-lore: 0
  base-lore: []
  bonus-lore: []
maximum-durability: 1.0
minimum-durability: 0.1
minimum-sockets: 0
maximum-sockets: 0
weight: 0.21
chance-to-drop-on-monster-death: 1.0
identity-weight: 0.21
chance-to-have-sockets: 1.0
broadcast-on-find: false
item-types:
  allowed-groups:
  - Wood
  - Stone
  - Leather
  - Gold
  - Rod
  - Bow
  - Crossbow
  disallowed-groups:
  - Diamond
  - Trident
  - Netherite
  - Iron
  - Chainmail
  allowed-material-ids: []
  disallowed-material-ids: []
minimum-distance-from-spawn: -1
maximum-distance-from-spawn: -1
unbreakable: false
chance-to-have-socket-extender-slots: 0.0
minimum-socket-extender-slots: 0
maximum-socket-extender-slots: 0
```
